#!/bin/sh 

files="*.cabal *.hs src"
exclude="(\.#.*|flymake).hs$"

do_build() {
  cabal build;
  if test $? ; then
      killall -q "hubbub-mock-subscriber" "hubbub" "hubbub-mock-publisher";
      start "hubbub-mock-subscriber" 
      start "hubbub"; 
      start "hubbub-mock-publisher";
  fi;
}

start() { 
  "dist/build/$1/$1" &
}

cabal configure --flag="mocks" && do_build

while $(inotifywait -qq -r --exclude $exclude -e modify -e create -e move $files) ; do
  do_build
done;
