#!/bin/sh 

files="*.cabal *.hs src"
exclude="(\.#.*|flymake).hs$"

do_build() {
  cabal build && (
    restart "hubbub"
    restart "hubbub-mock-publisher"
    restart "hubbub-mock-subscriber"
  )
}

restart() { 
  killall -q $1 
  dist/build/$1/$1 &
}

cabal configure && do_build

while $(inotifywait -qq -r --exclude $exclude -e modify -e create -e move $files) ; do
  do_build
done;
