#!/bin/sh 

files="*.cabal src test"
exclude="(\.#.*|flymake).hs$"

do_build() {
  cabal build && (cabal test || cat dist/test/*-Tests.log) 
}

cabal configure --enable-tests --flag="testing" && do_build

while $(inotifywait -qq -r --exclude $exclude -e modify -e create -e move $files) ; do
  do_build
done;  

